### ISSUE TITLE
Cannot create conda environment

### ISSUE THREAD

**Issue by daxus4** [aertslab/create_cisTarget_databases#18]
Hi everyone, I tried to create the conda environment by following the readme instruction.

When I use this command:
`
conda create -n create_cistarget_databases \
    'python=3.8' \
    'numpy=1.19.5' \
    'pandas>=1.2.0' \
    'pyarrow>=4.0.0' \
    'numba>=0.52.0' \
    'python-flatbuffers'
`

I obtain this error:

> Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - numpy=1.19.5
> 
> Current channels:
> 
>   - https://repo.anaconda.com/pkgs/main/linux-64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/linux-64
>   - https://repo.anaconda.com/pkgs/r/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org/
> 
> and use the search bar at the top of the page.

Is there a workaround?

Thanks, bye!

**Comment by ghuls** [comment]
Yes, it should work with more recent version of numpy (numba, pyarrow, pandas and python).
```
conda create -n create_cistarget_databases \
 'python=3.8' \
 'numpy>=1.19.5' \ 
 'pandas>=1.2.0' \
 'pyarrow>=4.0.0' \
 'numba>=0.52.0' \
 'python-flatbuffers'

**Comment by daxus4** [comment]
Thank you ghuls, now it work!

**Comment by ghuls** [comment]
conda create instructions are updated (It is not 100% necessary to have those versions, as older versions should also work).

**Comment by TingTingShao** [comment]
Hi, 

with 
```bash
conda create -n create_cistarget_databases \
    'python=3.10' \
    'numpy=1.21' \
    'pandas>=1.4.1' \
    'pyarrow>=7.0.0' \
    'numba>=0.55.1' \
    'python-flatbuffers'
```

The error occurs:
```bash
(create_cistarget_databases) bash-4.4$ $VSC_DATA/create_cisTarget_databases/create_cistarget_motif_databases.py -h
Traceback (most recent call last):
  File "/data/leuven/351/vsc35107/miniconda3/envs/create_cistarget_databases/lib/python3.10/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat import (
  File "/data/leuven/351/vsc35107/miniconda3/envs/create_cistarget_databases/lib/python3.10/site-packages/pandas/compat/__init__.py", line 26, in <module>
    from pandas.compat.numpy import is_numpy_dev
  File "/data/leuven/351/vsc35107/miniconda3/envs/create_cistarget_databases/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: this version of pandas is incompatible with numpy < 1.22.4
your numpy version is 1.21.6.
Please upgrade numpy to >= 1.22.4 to use this pandas version

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/leuven/351/vsc35107/create_cisTarget_databases/create_cistarget_motif_databases.py", line 19, in <module>
    import pandas as pd
  File "/data/leuven/351/vsc35107/miniconda3/envs/create_cistarget_databases/lib/python3.10/site-packages/pandas/__init__.py", line 28, in <module>
    raise ImportError(
ImportError: C extension: None not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext' to build the C extensions first.
```

Should I try the other version:
```
conda create -n create_cistarget_databases \
 'python=3.8' \
 'numpy>=1.19.5' \ 
 'pandas>=1.2.0' \
 'pyarrow>=4.0.0' \
 'numba>=0.52.0' \
 'python-flatbuffers'
```

Thanks,
tingting
