### ISSUE TITLE
404 not found of calibration file URL 

### ISSUE THREAD

**Issue by zhouxw27** [aertslab/create_cisTarget_databases#31]
The url of calibration file (https://resources.aertslab.org/cistarget/databases/sha256sum.txt) in cistarget database was invalid. Could anyone fix it?

**Comment by ghuls** [comment]
The documentation is currently out of date.
Each feather database has a corresponding sha1sum file.
```
https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg38/screen/mc_v10_clust/region_based/hg38_screen_v10_clust.regions_vs_motifs.rankings.feather
https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg38/screen/mc_v10_clust/region_based/hg38_screen_v10_clust.regions_vs_motifs.rankings.feather.sha1sum.txt
```

**Comment by zhouxw27** [comment]
The problem has already been solved. Thanks for answering my question.
