### ISSUE TITLE
Missing Feather data in cisTarget database

### ISSUE THREAD

**Issue by zhouxw27** [aertslab/create_cisTarget_databases#32]
The old feather data for R SCENIC analysis (https://resources.aertslab.org/cistarget/databases/old/homo_sapiens/hg19/refseq_r45/mc9nr/gene_based/hg19-tss-centered-10kb-7species.mc9nr.feather) was missing. Could anyone fix it? Thanks for answering my question.

**Comment by ghuls** [comment]
It is there now. Thanks for reporting.
